# Generated by Django 5.2.6 on 2026-09-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentOnboarding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(max_length=30, unique=True)),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("guardian_consent", models.BooleanField()),
                ("learning_difficulty", models.CharField(max_length=50)),
                ("age_band", models.CharField(max_length=20)),
                ("emergency_contact", models.CharField(max_length=15)),
                ("data_sharing_consent", models.BooleanField()),
            ],
        ),
    ]
